[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_VERSION = "20"
NIXPACKS_NO_MUSL = "1"
